"""初始化数据库模型

Revision ID: b8888de7362f
Revises: 
Create Date: 2026-04-25 15:39:03.777435
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8888de7362f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_index',
    sa.Column('arkhamdb_id', sa.String(length=16), nullable=False),
    sa.Column('name_zh', sa.String(length=128), nullable=False),
    sa.Column('name_en', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('cycle', sa.String(length=64), nullable=False),
    sa.Column('expansion', sa.String(length=64), nullable=False),
    sa.Column('is_double_sided', sa.Boolean(), nullable=False),
    sa.Column('mapping_status', sa.Enum('CONFIRMED', 'PENDING', 'ERROR', name='mappingstatus'), nullable=False),
    sa.PrimaryKeyConstraint('arkhamdb_id')
    )
    op.create_table('shared_card_backs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('back_url', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('errata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('arkhamdb_id', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('original_content', sa.Text(), nullable=False),
    sa.Column('modified_content', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='erratastatus'), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('review_note', sa.String(length=512), nullable=True),
    sa.Column('batch_id', sa.String(length=32), nullable=True),
    sa.Column('rendered_preview', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['arkhamdb_id'], ['card_index.arkhamdb_id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_errata_arkhamdb_id'), 'errata', ['arkhamdb_id'], unique=False)
    op.create_index(op.f('ix_errata_batch_id'), 'errata', ['batch_id'], unique=False)
    op.create_table('local_card_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('arkhamdb_id', sa.String(length=16), nullable=False),
    sa.Column('face', sa.String(length=4), nullable=False),
    sa.Column('relative_path', sa.String(length=256), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('last_modified', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['arkhamdb_id'], ['card_index.arkhamdb_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('relative_path')
    )
    op.create_index(op.f('ix_local_card_files_arkhamdb_id'), 'local_card_files', ['arkhamdb_id'], unique=False)
    op.create_table('tts_card_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('arkhamdb_id', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.Column('relative_json_path', sa.String(length=512), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('deck_key', sa.String(length=16), nullable=False),
    sa.Column('face_url', sa.Text(), nullable=False),
    sa.Column('back_url', sa.Text(), nullable=False),
    sa.Column('grid_width', sa.Integer(), nullable=False),
    sa.Column('grid_height', sa.Integer(), nullable=False),
    sa.Column('grid_position', sa.Integer(), nullable=False),
    sa.Column('unique_back', sa.Boolean(), nullable=False),
    sa.Column('cached_front_path', sa.String(length=256), nullable=True),
    sa.Column('cached_back_path', sa.String(length=256), nullable=True),
    sa.Column('shared_back_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['arkhamdb_id'], ['card_index.arkhamdb_id'], ),
    sa.ForeignKeyConstraint(['shared_back_id'], ['shared_card_backs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tts_card_images_arkhamdb_id'), 'tts_card_images', ['arkhamdb_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tts_card_images_arkhamdb_id'), table_name='tts_card_images')
    op.drop_table('tts_card_images')
    op.drop_index(op.f('ix_local_card_files_arkhamdb_id'), table_name='local_card_files')
    op.drop_table('local_card_files')
    op.drop_index(op.f('ix_errata_batch_id'), table_name='errata')
    op.drop_index(op.f('ix_errata_arkhamdb_id'), table_name='errata')
    op.drop_table('errata')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('shared_card_backs')
    op.drop_table('card_index')
    # ### end Alembic commands ###
